variables:
    REPO: aistcpsec/tee-distro-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

rootfs-riscv-debian-sid:
    tags:
        - fast-shells
    script:
        - docker build --rm -t ${REPO}:rootfs-riscv-debian-sid ./riscv/rootfs-debian-sid
        - docker run --privileged --rm -v $(pwd)/riscv/rootfs-debian-sid:/mnt ${REPO}:rootfs-riscv-debian-sid /bin/bash -c "/mnt/gen-debian.sh"
        - docker push ${REPO}:rootfs-riscv-debian-sid

rootfs-riscv-ubuntu-20.04:
    tags:
        - fast-shells
    script:
        - docker build --rm -t ${REPO}:rootfs-riscv-ubuntu-20.04 ./riscv/rootfs-ubuntu-20.04
        - docker run --privileged --rm -v $(pwd)/riscv/rootfs-ubuntu-20.04:/mnt ${REPO}:rootfs-riscv-ubuntu-20.04 /bin/bash -c "/mnt/gen-ubuntu-2004.sh"
        - docker push ${REPO}:rootfs-riscv-ubuntu-20.04

rootfs-arm64-ubuntu-20.04:
    variables:
         DOCKER_OUT_DIR: /mnt
         COMPRESSED_ROOTFS: arm64-20.04-rootfs.tar.xz
         ROOTFS_CONT_NME: rootfs-arm64-container
         ROOTFS_CONT_NME_1: rootfs-arm64-container-1
         ROOTFS_TAR_REPO: rootfs-arm64-ubuntu-20.04-tar
    tags:
        - fast-shells
    script:
        - docker build --rm -t ${REPO}:rootfs-arm64-ubuntu-20.04 ./arm64/rootfs-ubuntu-20.04
        - docker push ${REPO}:rootfs-arm64-ubuntu-20.04
        - docker run --privileged --name $ROOTFS_CONT_NME -v $(pwd)/arm64/rootfs-ubuntu-20.04:/mnt ${REPO}:rootfs-arm64-ubuntu-20.04 /bin/bash -c "/mnt/gen-ubuntu-2004.sh"
        - docker cp $ROOTFS_CONT_NME:${DOCKER_OUT_DIR}/${COMPRESSED_ROOTFS} $CI_PROJECT_DIR/${COMPRESSED_ROOTFS}
        - docker stop $ROOTFS_CONT_NME || true
        - docker rm $ROOTFS_CONT_NME || true
        - docker run --privileged --name $ROOTFS_CONT_NME_1 -itd -v $CI_PROJECT_DIR:${DOCKER_OUT_DIR} ${REPO}:rootfs-arm64-ubuntu-20.04
        - docker exec $ROOTFS_CONT_NME_1 cp ${DOCKER_OUT_DIR}/${COMPRESSED_ROOTFS} /
        - docker commit $ROOTFS_CONT_NME_1 ${REPO}:${ROOTFS_TAR_REPO}
        - docker push ${REPO}:${ROOTFS_TAR_REPO}
        - docker stop $ROOTFS_CONT_NME_1 || true
        - docker rm $ROOTFS_CONT_NME_1 || true

tee-distro-dev-doxygen_20.04:
    tags:
        - fast-shells
    script:
        - docker build --rm -t ${REPO}:doxygen-20.04 ./doxygen/20.04/
        - docker push ${REPO}:doxygen-20.04

tee-distro-dev-x64_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:x64-20.04 ./x64/20.04/
        - docker push ${REPO}:x64-20.04

tee-distro-dev-x64_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:x64-22.04 ./x64/22.04/
        - docker push ${REPO}:x64-22.04

tee-distro-dev-arm64_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --build-arg TOOLCHAIN_VERSION=3.10.0 --rm -t ${REPO}:arm64-20.04 ./arm64/20.04/
        - docker push ${REPO}:arm64-20.04

tee-distro-dev-arm64_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --build-arg TOOLCHAIN_VERSION=3.10.0 --rm -t ${REPO}:arm64-22.04 ./arm64/22.04/
        - docker push ${REPO}:arm64-22.04

tee-distro-dev-riscv_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:riscv-20.04 ./riscv/20.04/
        - docker push ${REPO}:riscv-20.04

tee-distro-dev-riscv_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:riscv-22.04 ./riscv/22.04/
        - docker push ${REPO}:riscv-22.04
