variables:
    REPO: aistcpsec/tee-distro-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

riscv-rootfs-debian-sid:
    tags:
        - fast-shells
    script:
        - docker build --rm -t riscv-debian-sid ./riscv/rootfs-debian-sid
        - docker run --privileged --rm -v $(pwd)/riscv/rootfs-debian-sid:/mnt riscv-debian-sid /bin/bash -c "/mnt/gen-debian.sh"

riscv-rootfs-ubuntu-20.04:
    tags:
        - fast-shells
    script:
        - docker build --rm -t riscv-ubuntu-2004 ./riscv/rootfs-ubuntu-20.04
        - docker run --privileged --rm -v $(pwd)/riscv/rootfs-ubuntu-20.04:/mnt riscv-ubuntu-2004 /bin/bash -c "/mnt/gen-ubuntu-2004.sh"

tee-distro-dev-doxygen_20.04:
    tags:
        - fast-shells
    script:
        - docker build --rm -t ${REPO}:doxygen-20.04 ./doxygen/20.04/
        - docker push ${REPO}:doxygen-20.04

tee-distro-dev-x64_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:x64-20.04 ./x64/20.04/
        - docker push ${REPO}:x64-20.04

tee-distro-dev-x64_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:x64-22.04 ./x64/22.04/
        - docker push ${REPO}:x64-22.04

tee-distro-dev-arm64_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --build-arg TOOLCHAIN_VERSION=3.10.0 --rm -t ${REPO}:arm64-20.04 ./arm64/20.04/
        - docker push ${REPO}:arm64-20.04

tee-distro-dev-arm64_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --build-arg TOOLCHAIN_VERSION=3.10.0 --rm -t ${REPO}:arm64-22.04 ./arm64/22.04/
        - docker push ${REPO}:arm64-22.04

tee-distro-dev-riscv_20.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:riscv-20.04 ./riscv/20.04/
        - docker push ${REPO}:riscv-20.04

tee-distro-dev-riscv_22.04:
    tags:
        - fast-shells
    script:
        - docker build --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:riscv-22.04 ./riscv/22.04/
        - docker push ${REPO}:riscv-22.04
