variables:
    ORG: trasioteam
    #DEBIAN_IMAGER_PIPELINE_TRIGGER_TOKEN: ca79f1c05d9f075e93fec2463c4087
    #DEBIAN_IMAGER_PIPELINE_TRIGGER_URL: https://192.168.100.100/api/v4/projects/108/trigger/pipeline

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

stages:
    - tee-dev
    - push-public

tee-dev-x86_20.04:
    stage: tee-dev
    tags:
        - shell117
    script:
        - docker build --rm -t ${ORG}/tee-dev-x64:20.04 ./tee-dev-x64/20.04/

    stage: tee-dev
    tags:
        - shell117
    script:
        - echo

tee-dev-riscv_20.04:
    stage: tee-dev
    tags:
        - shell117
    script:
        - echo

docker-push-public:
    stage: push-public
    tags:
        - shell117
    script:
        - docker push ${ORG}/tee-dev-x64:20.04
