variables:
    ORG: trasioteam2
    #DEBIAN_IMAGER_PIPELINE_TRIGGER_TOKEN: ca79f1c05d9f075e93fec2463c4087
    #DEBIAN_IMAGER_PIPELINE_TRIGGER_URL: https://192.168.100.100/api/v4/projects/108/trigger/pipeline

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

stages:
    - distro
    - push-public

tee-dev-x86_20.04:
    stage: build
    tags:
        - shell117
    script:
        - docker build --rm -t ${ORG}/tee-dev-x86:20.04 ./tee-dev-x86/20.04/

tee-dev-arm_20.04:
    stage: build
    tags:
        - shell117
    script:
        - echo

tee-dev-riscv_20.04:
    stage: build
    tags:
        - shell117
    script:
        - echo

