variables:
    REPO: aistcpsec/tee-distro-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

stages:
    - create-docker
    - push-public

tee-distro-dev-doxygen_20.04:
    stage: create-docker
    tags:
        - shell117
    script:
        - docker build --rm -t ${REPO}:doxygen-20.04 ./doxygen/20.04/

tee-distro-dev-x64_20.04:
    stage: create-docker
    tags:
        - shell117
    script:
        - docker build --rm -t ${REPO}:x64-20.04 ./x64/20.04/

tee-distro-dev-arm64_20.04:
    stage: create-docker
    tags:
        - shell117
    script:
        - docker build --build-arg TOOLCHAIN_VERSION=3.9.0 --rm -t ${REPO}:arm64-20.04 ./arm64/20.04/

tee-distro-dev-riscv_20.04:
    stage: create-docker
    tags:
        - shell117
    script:
        - docker build --rm -t ${REPO}:riscv-20.04 ./riscv/20.04/

docker-push-public:
    stage: push-public
    tags:
        - shell117
    script:
        - docker push ${REPO}:doxygen-20.04
        - docker push ${REPO}:x64-20.04
        - docker push ${REPO}:arm64-20.04
        - docker push ${REPO}:riscv-20.04
